name: Rebuild Documentation

on:
  release:
    types: [created]
  push:
    branches:
      - master  # Set a branch name to trigger deployment
  pull_request:

  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Generate and Deploy Documentation ✍🏼
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate documentation files
      uses: nikeee/docfx-action@v1.0.0
      with:
        args: Square9APIHelperLibrary/Documentation/docfx.json

    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2.2.0
      with:
        target_branch: gh-pages
        build_dir: Square9APIHelperLibrary/Documentation/_site
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
