name: Publish Dev DLL to GitHub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: nuget restore Square9APIHelperLibrary.sln

    - name: Build
      run: msbuild /p:Configuration=Release Square9APIHelperLibrary.sln

    - name: Publish release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "latest"
        prerelease: true
        title: "Latest Development Build"
        files: |
          ./Square9APIHelperLibrary/bin/Release/Square9APIHelperLibrary.dll